### ISSUE TITLE
Correcciones en el repo

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twE105-abel-diego-carlos#1]
Acordaos de renombrar vustro repo desde la pestaña Settings. Cambiadle el nombre a algo que tenga que ver con vuestra temática de proyecto y rellenad el Instrucciones.md con el contenido.
No aparece Carlos como asignable, comprobad que tiene acceso y si no que me mande un mail. 

Tened en cuenta que el README.md es el archivo prioritario del equipo, así que si lo cambiáis a otro nombre (Instrucciones.md) no va a aparecer desde el repo.

**Comment by abelbague** [comment]
> Hola llevo un rato intentando cambiar el nombre del repositorio pero no encuentro el settings correspondiente al repo y no si es que no tengo derechos suficientes para hacerlo. 

> Carlos no aparece como colaborador pero en su perfil si que aparece su actividad en el mismo asi que debe haber algun problema con eso. He intentado contactar con el pero no contesta.

> En cuanto al archivo Instrucciones.md debemos reemplazarlo por el Descripcion.md actual?

**Comment by MPerezMateo** [comment]
Me ha dicho Oscar que no hace falta renombrar el repo así que tranquilos, dejadlo como está.
En cuanto al "naming" de vuestro .md, podéis tener uno explicativo (Instrucciones.md o Descripción.md), pero debéis tener al menos un Readme.md que aparezca en cuanto accedéis a vuestro repo para dar a quien se meta en él una guía básica de lo que va vuestro proyecto. Recordad que sólo van a ver el archivo si se llama Readme.md así que debéis añadirlo. Hacedlo y cerramos la issue, solo son detallitos pero no cuesta nada cambiarlos. Ánimo y recordad que podéis contactar conmigo si tenéis cualquier duda.

**Comment by dhsanchez** [comment]
Ya hemos corregido el problema del Readme.md y demás; al final hemos optado por hacer una síntesis de los demás ficheros en el Readme y así poder cerrar el issue de una vez. Gracias por tu ayuda.

**Comment by MPerezMateo** [comment]
Perfect!
